### ISSUE TITLE
resetBoard() bad performance after calling method

### ISSUE THREAD

**Issue by qwerty084** [qwerty084/vue3-chessboard#193] opened 2023-06-14 20:30 UTC
**Describe the bug**
After calling resetBoard() method theres a delay after dropping a piece: [Violation] 'setTimeout' handler took ...ms

**Which version are you using**
1.1.8 (also happens on older versions)

**To Reproduce**
call resetBoard() -> move pieces 

**Expected behavior**
There should be no delay when dropping a piece.

**Comment by gavin-lb** [comment] 2023-06-21 18:34
This seems to happen any time the Chessground `movable.events.after` callback function is changed with `.set` API method. 

I thought perhaps this was then somehow related to Chess.js, but even when removing Chess.js functionality completely from the `movable.events.after` function (ie. never patching `.changeTurn` to it, just using some dummy function like `() => console.log('test')` and changing it to `() => console.log('test 2')` ), the same setTimeout violation behaviour is observed.

So then I thought perhaps this is a bug with Chessground when updating `movable.events.after` callback function. But it doesn't seem to be because when I tried to construct a minimal reproducible example I couldn't reproduce it in a barebones setting. See [this fiddle](https://jsfiddle.net/9hsz1xvn/) where (at least in my browser) the initial `movable.events.after` function causes setTimeout violations, but when changed to the shorter running function they stop. This is in contrast to the behaviour observed with the Vue component where a longer running function won't trigger any setTimeout violations, but when changed to a shorter running function, it will.

 So, I've no idea what's causing this...

**Comment by gavin-lb** [comment] 2023-06-21 20:09
Ok, I was mistaken before, it actually is specific to the `.changeTurn` method. For some reason it runs differently after being reassigned to the `movable.events.after` callback (even when assigned in the exact same way). 

[Here are two CPU profiles of `changeTurn`](https://github.com/qwerty084/vue3-chessboard/files/11824445/changeTurn.profiles.zip), where the shorter one is the profile of it running before `movable.events.after` is updated, and the longer after it is updated. 

It seems all the extra time is spent because of Vue reactivity? I'll do some more digging and see if I can figure out what's causing this.

**Comment by gavin-lb** [comment] 2023-06-23 13:25
The problem is caused because of the way Vue implements reactivity. Whenever you call a method of an object which is reactive in Vue, it binds `this` to a proxy of the object, rather than the object itself. 

So when BoardApi is first instantiated, `this` is exactly as you expect. However, whenever a method is called from within the Vue component, `this` is actually a proxy of the object with getters and setters for Vue to handle the reactivity. When the `resetBoard` method is called, these getters and setters propagate down into the assignment of the `movable.events.after` and so subsequent calls to `this.changeTurn` and create a bunch of unnecessary overhead. 

The solution is to **not** assign the BoardApi to a reactive variable, eg. 

```
<script setup lang="ts">
import { TheChessboard, type BoardApi } from '@/index';
import '@/assets/board.css';

let boardAPI: BoardApi;
</script>

<template>
  <TheChessboard @board-created="(api) => (boardAPI = api)" />
  <button @click="boardAPI.resetBoard">Reset Board</button>
</template>

<style>
body {
  background-color: #222;
}
</style>
```

This should fix the issue.

**Comment by qwerty084** [comment] 2023-06-23 20:41
Interesting. Thanks for investigating! I will update the readme and docs, to not use a ref.

**Closed** 2023-06-25 23:26 UTC
Labels: bug

**Comment by Modris** [comment] 2024-02-13 15:43
@gavin-lb you are a life-saver. I was scratching my head thinking why i have a huge delay between boardAPI updates.

 Initially i thought it was due to my for loops. I was using array with multiple boards for game history and just to load 5 new boards it took like a second. 50 boards took like 5 seconds. Now i can deploy 50 boards instantly.
